<option value="Amerika Serikat">Amerika Serikat</option>
<option value="Argentina">Argentina</option>
<option value="Australia">Australia</option>
<option value="Brazil">Brazil</option>
<option value="China">China</option>
<option value="India">India</option>
<option value="Indonesia" selected>Indonesia</option>
<option value="Inggris">Inggris</option>
<option value="Jepang">Jepang</option>
<option value="Jerman">Jerman</option>
<option value="Kanada">Kanada</option>
<option value="Korea Selatan">Korea Selatan</option>
<option value="Malaysia">Malaysia</option>
<option value="Meksiko">Meksiko</option>
<option value="Mesir">Mesir</option>
<option value="Rusia">Rusia</option>
<option value="Portugal">Portugal</option>
<option value="Saudi Arabia">Saudi Arabia</option>
<option value="Singapura">Singapura</option>
<option value="Spanyol">Spanyol</option>
<option value="Thailand">Thailand</option>
